# Generated by Django 5.0.2 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0007_bagitem_fragranceitem_watchitem_bagimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highjewelryitem',
            name='category',
            field=models.CharField(choices=[('bracelet', 'Bracelet'), ('ring', 'Ring'), ('necklace', 'Necklace'), ('earrings', 'Earrings'), ('watches', 'Watches')], max_length=20),
        ),
    ]
