# Generated by Django 5.0.2 on 2025-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_escolar_api', '0009_alter_highjewelryitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highjewelryitem',
            name='category',
            field=models.CharField(choices=[('bracelet', 'Bracelet'), ('ring', 'Ring'), ('necklace', 'Necklace'), ('earrings', 'Earrings'), ('watches', 'Watches'), ('accessories', 'Accessories'), ('fragrances', 'Fragrances')], max_length=20),
        ),
    ]
